apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-app
  labels:
    app: websocket-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-app
  template:
    metadata:
      labels:
        app: websocket-app
    spec:
      containers:
        - name: websocket-app
          image: nuclme/websocket-app:latest
          ports:
            - containerPort: 8088
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo-service:27017/admin